### PR TITLE
changing share link to work with unauth experiment

### PR DESCRIPTION
**Pull request by liechtym**
The /album/[id] route will help Jeff test the unauth album page. It is also backwards compatible because photos redirects /album/[id] to /albums/[id]

### CODE REVIEW

**Comment by jshcrowthe** [comment]
Relying on a legacy redirect IMO is something I'd avoid.

**Comment by liechtym** [comment]
@jshcrowthe If Jeff doesn't say anything, then we don't need to merge it until the unauthorized album experiment is on. I'm just concerned he's going to be upset about the share link not matching the new unauthenticated album url.

**Comment by jshcrowthe** [comment]
Then let's hold off until that is done.

**Comment by liechtym** [comment]
Sounds good

**Comment by jshcrowthe** [comment]
This hasn't been touched since May so I'm going to close it.

**Pull request closed without merging**
